//! Cross-language verification: the committed vectors were generated by
//! `keeper/scripts/gen-vectors.mjs` (TypeScript). This test proves the Rust
//! core independently agrees — same roots, same proof structure.

use owed_core::merkle::build;
use owed_core::register::{Register, RegisterEntry};

fn hex_to_32(s: &str) -> [u8; 32] {
    assert_eq!(s.len(), 64, "expected 32-byte hex");
    let mut out = [0u8; 32];
    for i in 0..32 {
        out[i] = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).expect("valid hex");
    }
    out
}

#[test]
fn golden_vectors_match_node_generator() {
    let txt = include_str!("../../shared/vectors/vectors.txt");
    assert!(!txt.is_empty(), "vectors.txt must be committed");

    let mut merkle_cases = 0usize;
    let mut register_cases = 0usize;

    for line in txt.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('|').collect();

        match parts[0] {
            "merkle" => {
                assert_eq!(parts.len(), 4, "merkle line: name|leaves|root");
                let leaves: Vec<[u8; 32]> = parts[2].split(',').map(hex_to_32).collect();
                let expected_root = hex_to_32(parts[3]);
                let (root, proofs) = build(&leaves);
                assert_eq!(
                    root, expected_root,
                    "case {}: Rust root != Node root",
                    parts[1]
                );
                // Every leaf's proof must also verify to the same root.
                for (i, l) in leaves.iter().enumerate() {
                    assert!(
                        proofs[i].verify_leaf(l, &root),
                        "case {}: proof {} failed",
                        parts[1],
                        i
                    );
                }
                merkle_cases += 1;
            }
            "register" => {
                assert_eq!(parts.len(), 3, "register line: name|root");
                // Mirrors the register case in the generator / register.rs tests.
                let mk = |n: u8, amt: u64| {
                    let mut o = [0u8; 32];
                    o[0] = n;
                    RegisterEntry::new(o, amt)
                };
                let reg = Register::new(vec![mk(9, 10), mk(3, 30), mk(5, 50), mk(1, 10)], 100)
                    .expect("register case must be valid");
                let (root, _) = reg.merkle_root_and_proofs();
                assert_eq!(
                    root,
                    hex_to_32(parts[2]),
                    "case {}: register root != Node register root",
                    parts[1]
                );
                register_cases += 1;
            }
            other => panic!("unknown vector kind: {other}"),
        }
    }

    // 17 small sizes + n=33 + 1 register case.
    assert_eq!(merkle_cases, 18, "expected 18 merkle cases");
    assert_eq!(register_cases, 1, "expected 1 register case");
}
